// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZQdqJ3TFeLeeQSnzA6MjUCSMgh_PqNS8',
    appId: '1:465648696477:web:90a5286245d0289f612874',
    messagingSenderId: '465648696477',
    projectId: 'english-app-ff17f',
    authDomain: 'english-app-ff17f.firebaseapp.com',
    storageBucket: 'english-app-ff17f.appspot.com',
    measurementId: 'G-7PDQ3CHJ1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyPFjW7h37V_gWMMTUrpBbfCwJfB0_Njw',
    appId: '1:465648696477:android:604f03086a7a380d612874',
    messagingSenderId: '465648696477',
    projectId: 'english-app-ff17f',
    storageBucket: 'english-app-ff17f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfssWuOz_SLxlRBHy_NOkdbkwbSwbNqfg',
    appId: '1:465648696477:ios:22ba74e877addb8d612874',
    messagingSenderId: '465648696477',
    projectId: 'english-app-ff17f',
    storageBucket: 'english-app-ff17f.appspot.com',
    iosClientId: '465648696477-c1s38jr1cejbc0nr1602k60v6rei337p.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfssWuOz_SLxlRBHy_NOkdbkwbSwbNqfg',
    appId: '1:465648696477:ios:34d002dc4550668f612874',
    messagingSenderId: '465648696477',
    projectId: 'english-app-ff17f',
    storageBucket: 'english-app-ff17f.appspot.com',
    iosClientId: '465648696477-6lncjesporakcnerfb12g1jo26v7sefa.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishApp.RunnerTests',
  );
}
